/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./activities/**/*.html"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#211b00",
        "surface-container-highest": "#e4e2e1",
        "inverse-on-surface": "#f3f0f0",
        background: "#fbf9f8",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "tertiary-fixed-dim": "#b8c8da",
        "secondary-container": "#f7e382",
        "surface-bright": "#fbf9f8",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#2d476f",
        "on-error": "#ffffff",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        primary: "#000a1e",
        tertiary: "#000c18",
        "on-background": "#1b1c1c",
        "inverse-primary": "#aec7f6",
        "on-tertiary-container": "#7b8b9b",
        "tertiary-container": "#132330",
        "surface-tint": "#465f88",
        "on-secondary-fixed-variant": "#524700",
        secondary: "#6c5e06",
        "on-surface-variant": "#44474e",
        "secondary-fixed-dim": "#dac769",
        "on-secondary-container": "#73640e",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2e1",
        "primary-container": "#002147",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae8e7",
        error: "#ba1a1a",
        surface: "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed": "#d4e4f6",
        "on-tertiary-fixed-variant": "#394857",
        "primary-fixed-dim": "#aec7f6",
        "secondary-fixed": "#f7e382",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#0d1d2a",
        "primary-fixed": "#d6e3ff",
        "on-primary-container": "#708ab5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "section-padding": "80px",
        "container-max": "1140px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        quote: ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "42px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        quote: ["22px", { lineHeight: "34px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
